"""Every generated file of the course, rendered from course/data/ and the lesson files.

    course/README.md                  language chooser
    course/<lang>/README.md           course home: tagline, roadmap infographic, outline
    course/<lang>/glossary.md         glossary page
    course/<lang>/diagrams/<id>.svg   one infographic per spec, plus roadmap.svg

Each learner-facing page is in one language and starts with the language bar
that links the same page in the other languages. Nothing here is edited by
hand: `python -m src.main build` writes these files, and the validator fails
when a committed copy differs from what this module renders.
"""

from __future__ import annotations

from src.core.infographics import render, render_roadmap
from src.core.model import (
    CHOOSER_FILE,
    ROADMAP,
    Course,
    Lesson,
    Module,
    diagram_path,
    language_dir,
    lesson_path,
    relative_link,
)
from src.utils.catalogs import translators_for
from src.utils.i18n import LANGUAGE_NAMES, Translator

GENERATED_NOTE = (
    "<!-- Generated by `python -m src.main build` from course/data/ and the lesson files. "
    "Do not edit by hand: CI fails when this file is out of date. -->"
)
TYPE_ICONS = {"concept": "📖", "demo": "🎬", "hands-on": "🛠️", "project": "🚀"}
LANGUAGE_BAR = "🌐 "


def language_name(language: str) -> str:
    return LANGUAGE_NAMES.get(language, language)


def language_bar(course: Course, language: str, path_for) -> str:
    """🌐 **This language** · [Other](link) · …, linking `path_for(other)` from `path_for(language)`."""
    here = path_for(language)
    parts = [
        f"**{language_name(other)}**" if other == language
        else f"[{language_name(other)}]({relative_link(here, path_for(other))})"
        for other in course.languages
    ]
    return LANGUAGE_BAR + " · ".join(parts)


def lesson_language_bar(course: Course, lesson_id: str, language: str) -> str:
    return language_bar(course, language, lambda other: lesson_path(lesson_id, other))


def home_path(language: str) -> str:
    return f"{language_dir(language)}/README.md"


def glossary_path(language: str) -> str:
    return f"{language_dir(language)}/glossary.md"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def term_label(entry: dict[str, str]) -> str:
    reading = entry.get("reading")
    return f"{entry['term']}［{reading}］" if reading else entry["term"]


def totals(course: Course, tr: Translator) -> str:
    return tr.t(
        "home.totals", modules=len(course.modules), units=len(course.units),
        lessons=len(course.lessons), minutes=course.total_minutes,
    )


def render_chooser(course: Course, translators: dict[str, Translator]) -> str:
    titles = " · ".join(dict.fromkeys(translators[language].t("chooser.title") for language in course.languages))
    lines = [GENERATED_NOTE, "", f"# 🌐 {titles}", ""]
    for language in course.languages:
        tr = translators[language]
        lines += [
            f"## [{language_name(language)} →]({language}/README.md)",
            "",
            f"**{course.title[language]}** — {course.tagline[language]}",
            "",
            f"[{tr.t('chooser.open')}]({language}/README.md) · [{tr.t('home.glossary')}]({language}/glossary.md)",
            "",
        ]
    return "\n".join(lines).rstrip() + "\n"


def render_home(course: Course, language: str, tr: Translator, started: set[str]) -> str:
    lines = [
        GENERATED_NOTE,
        "",
        language_bar(course, language, home_path),
        "",
        f"# {course.title[language]}",
        "",
        f"> {course.tagline[language]}",
        "",
        f"**{tr.t('home.audience')}** {course.audience[language]}",
        "",
        f"**{totals(course, tr)}** · [{tr.t('home.glossary')}](glossary.md)",
        "",
        f"![{tr.t('roadmap.title')}](diagrams/{ROADMAP}.svg)",
        "",
        f"_{tr.t('home.legend')}_",
        "",
    ]
    minimum = course.minimum_path_lessons
    if minimum:
        lines += [
            f"## {tr.t('home.minimum_heading')}",
            "",
            tr.t("home.minimum_intro", lessons=len(minimum), minutes=sum(lesson.minutes for lesson in minimum)),
            "",
        ]
        lines += [f"{step}. {_lesson_title(lesson, language, started)} — {tr.t('home.minutes', minutes=lesson.minutes)}"
                  for step, lesson in enumerate(minimum, start=1)]
        lines.append("")
    header = f"| # | {tr.t('home.lesson')} | {tr.t('home.type')} | {tr.t('home.time')} |"
    for module in course.modules:
        lines += [f"## {module.number}. {module.icon} {module.title[language]}", "", f"🎯 {module.goal[language]}", ""]
        for unit in module.units:
            track = "" if unit.track == "core" else f" · _{tr.t(f'home.track_{unit.track}')}_"
            lines += [f"### {unit.number} {unit.title[language]}{track}", "", header, "|---|---|---|---|"]
            for lesson in unit.lessons:
                title = _lesson_title(lesson, language, started)
                if lesson.id in course.minimum_path:
                    title = f"⭐ {title}"
                kind = f"{TYPE_ICONS[lesson.type]} {tr.t(f'lesson_types.{lesson.type}')}"
                lines.append(f"| {lesson.number} | {title} | {kind} | {tr.t('home.minutes', minutes=lesson.minutes)} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _lesson_title(lesson: Lesson, language: str, started: set[str]) -> str:
    """The lesson's title for a Markdown table or list, linked once its file exists."""
    title = _cell(lesson.title[language])
    return f"[{title}](lessons/{lesson.id}.md)" if lesson.id in started else title


def render_glossary(course: Course, language: str, tr: Translator) -> str:
    others = [other for other in course.languages if other != language]
    lines = [
        GENERATED_NOTE,
        "",
        language_bar(course, language, glossary_path),
        "",
        f"# {tr.t('glossary.title')}",
        "",
        tr.t("glossary.intro"),
        "",
        f"| {tr.t('glossary.term')} | {tr.t('glossary.definition')} | "
        + " | ".join(language_name(other) for other in others) + " |",
        "|---|---|" + "---|" * len(others),
    ]
    for term in course.glossary.values():
        entry = term.entries[language]
        cells = [f"**{_cell(term_label(entry))}**", _cell(entry["definition"])]
        cells += [_cell(term_label(term.entries[other])) for other in others]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def roadmap_svg(course: Course, language: str, tr: Translator) -> str:
    modules = [
        {
            "number": module.number,
            "icon": module.icon,
            "title": module.title[language],
            "meta": tr.t(
                "roadmap.meta", lessons=len(module.lessons),
                minutes=sum(lesson.minutes for lesson in module.lessons),
            ) + _minimum_count(course, module, tr),
        }
        for module in course.modules
    ]
    labels = {
        "title": tr.t("roadmap.title"),
        "subtitle": totals(course, tr),
        "start": tr.t("roadmap.start"),
        "finish": tr.t("roadmap.finish"),
    }
    return render_roadmap(modules, labels, language)


def _minimum_count(course: Course, module: Module, tr: Translator) -> str:
    count = sum(lesson.id in course.minimum_path for lesson in module.lessons)
    return f" · {tr.t('roadmap.minimum', lessons=count)}" if count else ""


def generated_files(course: Course, started: set[str]) -> dict[str, str]:
    """Repository-relative path -> content of every generated file.

    `started` holds the ids of lessons that have files; the course homes link
    only those.
    """
    translators = translators_for(course.languages)
    files = {CHOOSER_FILE: render_chooser(course, translators)}
    for language in course.languages:
        tr = translators[language]
        files[home_path(language)] = render_home(course, language, tr, started)
        files[glossary_path(language)] = render_glossary(course, language, tr)
        files[diagram_path(ROADMAP, language)] = roadmap_svg(course, language, tr)
        for diagram_id, spec in course.diagrams.items():
            files[diagram_path(diagram_id, language)] = render(spec, language)
    return files
